name: Build and Test
on:
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rust-src
      - name: Install wasm-pack
        run: cargo install wasm-pack --version 0.12.1
      - name: Build wasm release
        run: ./build-release.sh
      - name: Run test
        run: cargo test
