name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rust-src
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm release
        run: ./build-release.sh
      - name: Run test
        run: cargo test
