name: Release

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rust-src
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm release
        run: ./build-release.sh
      - name: Run test
        run: cargo test
      - name: Validate release
        uses: manovotny/github-releases-for-automated-package-publishing-action@v1.0.0
      - run: npm config set "//npm.pkg.github.com/:_authToken" "${CONMAN124_GITHUB_TOKEN}"
        env:
          NPM_CONFIG_CONMAN124_GITHUB_TOKEN: ${{secrets.CONMAN124_GITHUB_TOKEN}}
      - run: npm config list
        env:
          NPM_CONFIG_CONMAN124_GITHUB_TOKEN: ${{secrets.CONMAN124_GITHUB_TOKEN}}
      - run: npm publish
        working-directory: pkg
        env:
          NPM_CONFIG_CONMAN124_GITHUB_TOKEN: ${{secrets.CONMAN124_GITHUB_TOKEN}}
